# Generated by Django 3.0.4 on 2020-04-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200323_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
