# Generated by Django 3.0.4 on 2020-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20200415_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Start time'),
        ),
    ]
