# Generated by Django 3.0.4 on 2020-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20200415_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True, verbose_name='Book date'),
        ),
    ]
