# Generated by Django 3.0.4 on 2020-04-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200415_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagePath',
            field=models.CharField(default='Image/test.img', max_length=30, null=True),
        ),
    ]
