# Generated by Django 3.0.4 on 2020-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_event_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imagePath',
            field=models.CharField(default='Image/test.png', max_length=30, null=True),
        ),
    ]
