# Generated by Django 3.0.4 on 2020-04-25 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0012_auto_20200421_0252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='organization',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(help_text='add organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
