# Generated by Django 3.0.4 on 2020-04-28 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20200425_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Booking')),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.Event')),
            ],
        ),
    ]
