# Generated by Django 3.0.4 on 2020-04-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='eventId',
        ),
    ]
