# Generated by Django 3.0.4 on 2020-04-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_ticket_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested',
            field=models.IntegerField(default=0, verbose_name='# people interested'),
        ),
    ]
