# Generated by Django 3.0.4 on 2020-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_auto_20200503_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.RenameField(
            model_name='event',
            old_name='fee',
            new_name='baseFee',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='ticketOptions',
            field=models.ManyToManyField(related_name='options', to='Home.TicketOption'),
        ),
    ]
