# Generated by Django 3.0.4 on 2020-05-14 00:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0021_auto_20200503_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, help_text='add organizer', null=True, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
